Repository hosiker/SNS_App_Project, pull requests merged in 2023-08, with the labels that each got.

#9 [UI]merge
  .gradle/8.0/checksums/checksums.lock
  .gradle/8.0/checksums/md5-checksums.bin
  .gradle/8.0/checksums/sha1-checksums.bin
  .gradle/8.0/executionHistory/executionHistory.bin
  .gradle/8.0/executionHistory/executionHistory.lock
  .gradle/8.0/fileHashes/fileHashes.bin
  .gradle/8.0/fileHashes/fileHashes.lock
  .gradle/8.0/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  app/src/main/java/com/example/nbcamp_15ya_sns/DetailActivity.kt
  app/src/main/res/drawable/gyujin.jpg
  app/src/main/res/drawable/hosick.jpg
  app/src/main/res/drawable/jaeyong.jpg
  app/src/main/res/drawable/jisung.jpg
  app/src/main/res/drawable/seungyoon.jpg
  app/src/main/res/layout/detail_activity.xml
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/my_page_activity.xml
  app/src/main/res/layout/user_list_activity.xml
Labels: UI

#10 [Layout]로그인화면
  .gradle/8.0/executionHistory/executionHistory.bin
  .gradle/8.0/executionHistory/executionHistory.lock
  .gradle/8.0/fileHashes/fileHashes.bin
  .gradle/8.0/fileHashes/fileHashes.lock
  .gradle/8.0/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  app/src/main/res/drawable/ic_logo_15ya.png
  app/src/main/res/layout/login_activity.xml
Labels: UI

#13 Feature/detailpageHs
  .gradle/8.0/checksums/checksums.lock
  .gradle/8.0/checksums/md5-checksums.bin
  .gradle/8.0/checksums/sha1-checksums.bin
  .gradle/8.0/executionHistory/executionHistory.bin
  .gradle/8.0/executionHistory/executionHistory.lock
  .gradle/8.0/fileHashes/fileHashes.bin
  .gradle/8.0/fileHashes/fileHashes.lock
  .gradle/8.0/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  app/build.gradle
  app/src/main/java/com/example/nbcamp_15ya_sns/DetailActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/friendManager.kt
  app/src/main/res/layout/detail_activity.xml
Labels: UI

#16 Feature/mainpagedummy js
  app/src/main/java/com/example/nbcamp_15ya_sns/LoginActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/MainActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/StartActivity.kt
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/layout/main_activity.xml
Labels: UI

#15 [FEAT] : 로그인화면 한영전환 구현
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: feat

#17 [FEAT] Data
  app/src/main/java/com/example/nbcamp_15ya_sns/FriendDB.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/LoginActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/MainActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/MyPageActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/SiginUpActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/UserDB.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/UserListActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/UserManager.kt
Labels: feat

#18 [DOCS] : 📚 ️ 영/한 변환 기능 완료
  .gradle/8.0/executionHistory/executionHistory.bin
  .gradle/8.0/executionHistory/executionHistory.lock
  .gradle/8.0/fileHashes/fileHashes.bin
  .gradle/8.0/fileHashes/fileHashes.lock
  .gradle/8.0/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  app/src/main/java/com/example/nbcamp_15ya_sns/DetailActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/LoginActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/SiginUpActivity.kt
  app/src/main/res/layout/detail_activity.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/my_page_activity.xml
  app/src/main/res/layout/sigin_up_activity.xml
  app/src/main/res/layout/user_list_activity.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: documentation

#19 [Bug][UI] 하단버튼 이동 버그 수정 및 회원가입 영문버전 수정
  .gradle/8.0/fileHashes/fileHashes.lock
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/nbcamp_15ya_sns/SiginUpActivity.kt
  app/src/main/res/layout/sigin_up_activity.xml
  app/src/main/res/layout/user_list_activity.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, UI

#20 [FIX] : 메인페이지 더미데이터 완료
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/drawable/ic_mainpage_photo0.jpg
  app/src/main/res/drawable/ic_mainpage_photo1.jpg
  app/src/main/res/drawable/ic_mainpage_photo3.jpg
  app/src/main/res/drawable/ic_mainpage_photo4.jpg
  app/src/main/res/layout/main_activity.xml
Labels: fix

#21 [Layout] 로그인, 유저리스트, 마이페이지, 디테일페이지 영문변환시 짤리는거 및 하단바 수정
  .gradle/8.0/checksums/checksums.lock
  .gradle/8.0/checksums/md5-checksums.bin
  .gradle/8.0/checksums/sha1-checksums.bin
  .gradle/8.0/executionHistory/executionHistory.bin
  .gradle/8.0/executionHistory/executionHistory.lock
  .gradle/8.0/fileHashes/fileHashes.bin
  .gradle/8.0/fileHashes/fileHashes.lock
  .gradle/8.0/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  app/src/main/java/com/example/nbcamp_15ya_sns/MyPageActivity.kt
  app/src/main/res/layout/detail_activity.xml
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/layout/my_page_activity.xml
  app/src/main/res/layout/user_list_activity.xml
Labels: fix

#23 [fix] 백버튼 삭제 및 mbti버그수정
  app/src/main/java/com/example/nbcamp_15ya_sns/MyPageActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/SiginUpActivity.kt
  app/src/main/res/layout/my_page_activity.xml
Labels: fix

#25 [Repact] 함수 private화 및 코드 패키징
  .gradle/8.0/fileHashes/fileHashes.lock
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/nbcamp_15ya_sns/DetailActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/Friend.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/FriendDB.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/LoginActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/MainActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/MyPageActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/SiginUpActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/StartActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/User.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/UserDB.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/UserListActivity.kt
  app/src/main/java/com/example/nbcamp_15ya_sns/UserManager.kt
  app/src/main/res/layout/detail_activity.xml
  app/src/main/res/layout/login_activity.xml
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/my_page_activity.xml
  app/src/main/res/layout/sigin_up_activity.xml
  app/src/main/res/layout/start_activity.xml
  app/src/main/res/layout/user_list_activity.xml
Labels: ReFact
